[project]
name = "pick-a"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "requests>=2.32.5",
    "playwright>=1.57.0",
    "flask>=3.0.0",
    "flask-cors>=4.0.0",
    "gunicorn>=23.0.0",
]
