[project]
name = "pick-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "requests>=2.32.5",
]
